services:
  ssb_frontend:
    image: southsuburbs-frontend:latest
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=3072
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    restart: unless-stopped

  lgr-backend:
    image: klirtrak-voice-backend:latest
    container_name: lgr-backend
    restart: always
    env_file: .env
    ports:
      - "3000:3000"
      - "8055:8055"
    entrypoint: ["/usr/local/bin/node", "/app/node_modules/.bin/directus", "start"]
